package net.irisshaders.iris.vulkan;

import com.mojang.renderpearl.api.pipeline.RenderPipeline;
import com.mojang.renderpearl.api.GpuFormat;
import com.mojang.renderpearl.api.commands.CommandEncoder;
import com.mojang.renderpearl.api.commands.RenderPass;
import com.mojang.renderpearl.api.commands.RenderPassDescriptor;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.renderpearl.api.textures.GpuSampler;
import com.mojang.renderpearl.api.textures.GpuTexture;
import com.mojang.renderpearl.api.textures.GpuTextureView;
import com.mojang.renderpearl.api.textures.FilterMode;
import net.irisshaders.iris.Iris;
import net.irisshaders.iris.backend.IrisBackend;
import net.irisshaders.iris.pipeline.WorldRenderingPhase;
import net.irisshaders.iris.pipeline.WorldRenderingPipeline;
import net.irisshaders.iris.shaderpack.programs.ProgramSet;
import net.minecraft.client.Minecraft;
import org.joml.Vector4fc;

import java.util.Arrays;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

public final class IrisVulkanGbufferTargets {
	public static final int COLOR_TARGET_COUNT = IrisVulkanTargetIndices.LOGICAL_TARGET_COUNT;
	public static final int MAX_COLOR_ATTACHMENTS = IrisVulkanTargetIndices.MAX_COLOR_ATTACHMENTS;
	public static final int FALLBACK_SCENE_TARGET = 4;
	public static final int FINAL_SOURCE_TARGET = 3;
	private static final int[] DEFAULT_TERRAIN_DRAW_BUFFERS = {6, 7, 3};

	private static final IrisVulkanTargetModel targetModel = new IrisVulkanTargetModel();
	private static boolean frameOpen;
	private static boolean frameActive;
	private static boolean currentFrameMainColorCopyAvailable;
	private static int[] activeDrawBuffers = DEFAULT_TERRAIN_DRAW_BUFFERS;
	private static boolean loggedCapture;
	private static final Set<String> loggedCaptureRejections = new HashSet<>();
	// GL enables mip sampling only on the physical image generated by a pass,
	// then resets it at the frame boundary. Allocation alone does not enable it.
	private static final Set<GpuTexture> mipSamplingEnabled = java.util.Collections.newSetFromMap(new java.util.IdentityHashMap<>());
	private static GpuTextureView depthTexture0;
	private static GpuTextureView depthTexture1;
	private static GpuTextureView depthTexture2;
	private static final GpuTexture[] depthSnapshots = new GpuTexture[3];
	private static final GpuTextureView[] depthSnapshotViews = new GpuTextureView[3];
	private static GpuTexture handDepthScratch;
	private static GpuTextureView handDepthScratchView;
	private static final GpuTexture[] feedbackSnapshots = new GpuTexture[COLOR_TARGET_COUNT];
	private static final GpuTextureView[] feedbackViews = new GpuTextureView[COLOR_TARGET_COUNT];
	private static ProgramSet feedbackPrograms;
	private static IrisVulkanFeedbackPlan feedbackPlan = IrisVulkanFeedbackPlan.unknown("No program set selected");
	private static long feedbackCopies, feedbackCopiesSkipped, feedbackBoundaries;

	private IrisVulkanGbufferTargets() {
	}

	public static void beginFrameCapture() {
		if (!IrisBackend.isVulkan(RenderSystem.getDevice()) || !IrisNativeVulkan.shouldCaptureGbuffers()) {
			return;
		}

		frameOpen = true;
		mipSamplingEnabled.clear();
		frameActive = false;
		currentFrameMainColorCopyAvailable = false;
		activeDrawBuffers = Arrays.copyOf(DEFAULT_TERRAIN_DRAW_BUFFERS, DEFAULT_TERRAIN_DRAW_BUFFERS.length);
		if (IrisNativeVulkan.worldDevelopmentEnabled()) {
			var main = Minecraft.getInstance().gameRenderer.mainRenderTarget();
			ensure(main.getColorTexture());
			CommandEncoder encoder = RenderSystem.getDevice().createCommandEncoder();
			currentFrameMainColorCopyAvailable = seedTargets(encoder, main.getColorTextureView());
			frameActive = true;
			ensureDepthSnapshots(main.getDepthTexture());
			for (GpuTexture depth : depthSnapshots) encoder.clearColorTexture(depth, new org.joml.Vector4f(1, 0, 0, 1));
			setDepthTextureViews(depthSnapshotViews[0], depthSnapshotViews[1], depthSnapshotViews[2]);
		}
	}

	/** Accept world targets by image identity, never by an untrusted pass label. */
	public static boolean isWorldPass(RenderPassDescriptor descriptor) {
		if (!frameOpen || !IrisNativeVulkan.worldDevelopmentEnabled() || IrisVulkanShadowRenderer.active()
			|| !IrisNativeVulkan.shouldCaptureGbuffers() || descriptor.colorAttachments().size() != 1) return false;
		var attachment = descriptor.colorAttachments().getFirst();
		if (attachment == null || attachment.textureView() == null) return false;
		var main = Minecraft.getInstance().gameRenderer.mainRenderTarget();
		GpuTexture texture = attachment.textureView().texture();
		return texture == main.getColorTexture() || (isMainSizedColorTarget(texture, main.getColorTexture())
			&& descriptor.depthAttachment() != null
			&& descriptor.depthAttachment().textureView().texture() == main.getDepthTexture());
	}

	public static RenderPassDescriptor routeWorldPass(RenderPassDescriptor descriptor, int[] drawBuffers) {
		IrisVulkanTargetIndices.validateDrawBuffers("native world program", drawBuffers);
		if (!frameActive || !ready()) throw new IllegalStateException("Native world targets are not initialized");
		List<RenderPassDescriptor.Attachment<Optional<Vector4fc>>> attachments = new ArrayList<>();
		for (int target : drawBuffers) {
			GpuTextureView view = currentView(target);
			if (view == null) throw new IllegalStateException("World program writes undeclared colortex" + target);
			attachments.add(new RenderPassDescriptor.Attachment<>(view, Optional.empty()));
		}
		return new RenderPassDescriptor(descriptor.label(), attachments, descriptor.depthAttachment(), descriptor.renderArea());
	}

	/** Freeze inputs at a world-stage boundary for programs that also write that target. */
	public static void snapshotWorldInputs() {
		if (!frameOpen) return;
		feedbackBoundaries++;
		CommandEncoder encoder = null;
		for (int i=0; i<COLOR_TARGET_COUNT; ++i) {
			GpuTexture source = currentTexture(i);
			if (source == null) continue;
			if (!feedbackPlan.needs(i)) { feedbackCopiesSkipped++; continue; }
			if (encoder == null) encoder = RenderSystem.getDevice().createCommandEncoder();
			GpuTexture copy = feedbackSnapshots[i];
			if (copy == null || copy.getWidth(0) != source.getWidth(0) || copy.getHeight(0) != source.getHeight(0)
				|| copy.getFormat() != source.getFormat()) {
				if (feedbackViews[i] != null) feedbackViews[i].close();
				if (copy != null) copy.close();
				final int target = i;
				copy = RenderSystem.getDevice().createTexture(() -> "Iris native world input colortex"+target,
					GpuTexture.USAGE_COPY_DST | GpuTexture.USAGE_TEXTURE_BINDING,
					source.getFormat(), source.getWidth(0), source.getHeight(0), 1, 1);
				feedbackSnapshots[i] = copy;
				feedbackViews[i] = RenderSystem.getDevice().createTextureView(copy);
			}
			encoder.copyTextureToTexture(source, copy, 0, 0, 0, 0, 0, source.getWidth(0), source.getHeight(0));
			feedbackCopies++;
		}
	}

	/** Read-only counters for comparing retained snapshot work with the original all-target path. */
	public static long feedbackSnapshotCopies() { return feedbackCopies; }
	public static long feedbackSnapshotCopiesSkipped() { return feedbackCopiesSkipped; }
	public static long feedbackSnapshotBoundaries() { return feedbackBoundaries; }

	public static GpuTextureView feedbackView(int target) {
		return target < 0 || target >= COLOR_TARGET_COUNT || !feedbackPlan.needs(target) ? null : feedbackViews[target];
	}

	private static void ensureDepthSnapshots(GpuTexture mainDepth) {
		if (mainDepth == null) throw new IllegalStateException("Native world has no depth texture");
		if (depthSnapshots[0] != null && depthSnapshots[0].getWidth(0) == mainDepth.getWidth(0)
			&& depthSnapshots[0].getHeight(0) == mainDepth.getHeight(0)
			&& depthSnapshots[0].getFormat() == GpuFormat.R32_FLOAT) return;
		closeDepthSnapshots();
		for (int i = 0; i < depthSnapshots.length; ++i) {
			final int index = i;
			depthSnapshots[i] = RenderSystem.getDevice().createTexture(() -> "Iris native depthtex" + index,
				GpuTexture.USAGE_COPY_DST | GpuTexture.USAGE_COPY_SRC | GpuTexture.USAGE_TEXTURE_BINDING | GpuTexture.USAGE_RENDER_ATTACHMENT,
				GpuFormat.R32_FLOAT, mainDepth.getWidth(0), mainDepth.getHeight(0), 1, 1);
			depthSnapshotViews[i] = RenderSystem.getDevice().createTextureView(depthSnapshots[i]);
		}
	}

	/** Snapshot at the opaque/translucent/hand boundaries; never sample an attached image. */
	public static void snapshotOpaqueDepths() {
		if (!frameOpen) return;
		var main = Minecraft.getInstance().gameRenderer.mainRenderTarget();
		ensureDepthSnapshots(main.getDepthTexture());
		IrisVulkanDepthCopy.copyOpaque(RenderSystem.getDevice().createCommandEncoder(), main.getDepthTextureView(),
			depthSnapshotViews[0], depthSnapshotViews[1], depthSnapshotViews[2]);
	}

	/** Refresh an individual snapshot only at its later independent lifecycle boundary. */
	public static void snapshotDepth(int index) {
		if (!frameOpen || index < 0 || index >= depthSnapshots.length) return;
		GpuTexture source = Minecraft.getInstance().gameRenderer.mainRenderTarget().getDepthTexture();
		ensureDepthSnapshots(source);
		IrisVulkanDepthCopy.copy(RenderSystem.getDevice().createCommandEncoder(),
			Minecraft.getInstance().gameRenderer.mainRenderTarget().getDepthTextureView(), depthSnapshotViews[index]);
	}

	private static void closeDepthSnapshots() {
		if (handDepthScratchView != null) handDepthScratchView.close();
		if (handDepthScratch != null) handDepthScratch.close();
		handDepthScratchView = null;
		handDepthScratch = null;
		for (int i=0; i<depthSnapshots.length; ++i) {
			if (depthSnapshotViews[i] != null) depthSnapshotViews[i].close();
			if (depthSnapshots[i] != null) depthSnapshots[i].close();
			depthSnapshotViews[i] = null;
			depthSnapshots[i] = null;
		}
	}

	public static void captureSolidHandDepth() {
		if (!frameOpen || !frameActive || depthSnapshotViews[1] == null) return;
		if (handDepthScratch == null) {
			GpuTexture opaque = depthSnapshots[1];
			handDepthScratch = RenderSystem.getDevice().createTexture(() -> "Iris solid hand depth merge",
				GpuTexture.USAGE_RENDER_ATTACHMENT | GpuTexture.USAGE_TEXTURE_BINDING | GpuTexture.USAGE_COPY_SRC | GpuTexture.USAGE_COPY_DST,
				GpuFormat.R32_FLOAT, opaque.getWidth(0), opaque.getHeight(0), 1, 1);
			handDepthScratchView = RenderSystem.getDevice().createTextureView(handDepthScratch);
		}
		IrisVulkanDepthCopy.mergeSolidHand(RenderSystem.getDevice().createCommandEncoder(),
			Minecraft.getInstance().gameRenderer.mainRenderTarget().getDepthTextureView(), depthSnapshotViews[2],
			depthSnapshotViews[1], handDepthScratchView);
		GpuTexture oldTexture = depthSnapshots[1];
		GpuTextureView oldView = depthSnapshotViews[1];
		depthSnapshots[1] = handDepthScratch;
		depthSnapshotViews[1] = handDepthScratchView;
		handDepthScratch = oldTexture;
		handDepthScratchView = oldView;
		setDepthTextureViews(depthSnapshotViews[0], depthSnapshotViews[1], depthSnapshotViews[2]);
	}

	public static RenderPassDescriptor rewriteMainRenderPass(CommandEncoder encoder, RenderPassDescriptor descriptor) {
		if (!IrisBackend.isVulkan(RenderSystem.getDevice())) {
			return rejectCapture(descriptor, "render backend is not Vulkan");
		}
		if (!frameOpen) {
			return rejectCapture(descriptor, "frame capture is not open");
		}
		if (Iris.getCurrentPack().isEmpty()) {
			return rejectCapture(descriptor, "no shaderpack is active");
		}

		String label = descriptor.label().get();
		if (label == null) {
			label = "";
		}
		WorldRenderingPhase phase = currentTerrainCapturePhase();
		boolean sodiumTerrainPass = label.equalsIgnoreCase("Terrain");
		if (phase == WorldRenderingPhase.NONE && !sodiumTerrainPass) {
			return rejectCapture(descriptor, "current Iris phase is not opaque terrain: " + label);
		}
		if (shouldSkipCaptureLabel(label)) {
			return rejectCapture(descriptor, "render-pass label is excluded: " + label);
		}

		if (descriptor.depthAttachment() == null || descriptor.colorAttachments().size() != 1) {
			return rejectCapture(descriptor, "render pass does not have one color attachment plus depth");
		}

		RenderPassDescriptor.Attachment<Optional<Vector4fc>> first = descriptor.colorAttachments().getFirst();

		if (first == null) {
			return rejectCapture(descriptor, "render pass has a null color attachment");
		}

		if (first.textureView() == null) {
			return rejectCapture(descriptor, "render pass has a null color texture view");
		}

		GpuTexture colorTexture = first.textureView().texture();
		GpuTexture mainColorTexture = Minecraft.getInstance().gameRenderer.mainRenderTarget().getColorTexture();

		if (!isMainSizedColorTarget(colorTexture, mainColorTexture)) {
			return rejectCapture(descriptor, "color attachment is not the copyable main-sized target");
		}

		int[] drawBuffers = phase == WorldRenderingPhase.NONE
			? Arrays.copyOf(DEFAULT_TERRAIN_DRAW_BUFFERS, DEFAULT_TERRAIN_DRAW_BUFFERS.length)
			: IrisNativeVulkan.getDrawBuffersForPhase(phase);

		if (drawBuffers.length == 0) {
			return rejectCapture(descriptor, "shaderpack terrain program has no draw buffers");
		}
		if (!validDrawBuffers(drawBuffers)) {
			Iris.logger.warn("Rejecting native Vulkan draw-buffer selection {}; expected at most {} distinct logical targets in 0..{}.",
				Arrays.toString(drawBuffers), MAX_COLOR_ATTACHMENTS, COLOR_TARGET_COUNT - 1);
			return rejectCapture(descriptor, "invalid or excessive color attachments");
		}

		if (ensure(colorTexture)) {
			frameActive = false;
			currentFrameMainColorCopyAvailable = false;
			loggedCapture = false;
		}
		if (!ready()) {
			return rejectCapture(descriptor, "gbuffer targets are not ready");
		}
		for (int drawBuffer : drawBuffers) {
			if (!targetModel.isAllocated(drawBuffer)) {
				return rejectCapture(descriptor, "colortex" + drawBuffer + " was not declared or selected by the shaderpack");
			}
		}

		if (!frameActive) {
			currentFrameMainColorCopyAvailable = seedTargets(encoder, first.textureView());
			frameActive = true;
		}

		activeDrawBuffers = Arrays.copyOf(drawBuffers, drawBuffers.length);
		List<RenderPassDescriptor.Attachment<Optional<Vector4fc>>> attachments = new ArrayList<>();

		for (int drawBuffer : activeDrawBuffers) {
			attachments.add(new RenderPassDescriptor.Attachment<>(currentView(drawBuffer), Optional.empty()));
		}

		if (!loggedCapture) {
			loggedCapture = true;
			Iris.logger.info("Capturing native Vulkan gbuffers into colortex draw buffers {} from {}.",
				Arrays.toString(activeDrawBuffers), label);
		}

		return new RenderPassDescriptor(descriptor.label(), attachments, descriptor.depthAttachment(), descriptor.renderArea());
	}

	public static RenderPipeline adaptPipelineForGbufferPass(RenderPipeline pipeline,
															 List<RenderPassDescriptor.Attachment<Optional<Vector4fc>>> colorAttachments) {
		int attachmentCount = drawBuffersForAttachments(colorAttachments).length;

		if (attachmentCount == 0) {
			return pipeline;
		}

		List<GpuFormat> attachmentFormats = new ArrayList<>(attachmentCount);
		for (int i = 0; i < attachmentCount; i++) {
			RenderPassDescriptor.Attachment<Optional<Vector4fc>> attachment = colorAttachments.get(i);
			GpuTextureView view = attachment.textureView();
			if (view == null || view.isClosed()) {
				return pipeline;
			}

			GpuTexture texture = view.texture();
			if (texture == null || texture.isClosed()) {
				return pipeline;
			}

			attachmentFormats.add(texture.getFormat());
		}

		if (IrisNativeVulkan.worldDevelopmentEnabled()) {
			var key = IrisNativeVulkan.worldShaderKey(pipeline);
			return IrisVulkanWorldPipelineStates.adapt(pipeline, key, IrisNativeVulkan.getWorldDirectives(key),
				attachmentFormats, drawBuffersForAttachments(colorAttachments));
		}
		return IrisNativeVulkan.compatiblePipelineForGbufferPass(pipeline, attachmentFormats);
	}

	public static int[] drawBuffersForAttachments(List<RenderPassDescriptor.Attachment<Optional<Vector4fc>>> colorAttachments) {
		if (IrisNativeVulkan.worldDevelopmentEnabled() && ready() && colorAttachments != null) {
			int[] indices = new int[colorAttachments.size()];
			for (int i=0; i<indices.length; ++i) {
				indices[i] = -1;
				var attachment = colorAttachments.get(i);
				for (int target=0; attachment != null && target<COLOR_TARGET_COUNT; ++target) {
					if (attachment.textureView() != null && attachment.textureView() == currentView(target)) { indices[i]=target; break; }
				}
				if (indices[i] < 0) return new int[0];
			}
			return indices;
		}
		if (!ready() || colorAttachments == null || colorAttachments.size() != activeDrawBuffers.length
			|| !validDrawBuffers(activeDrawBuffers)) {
			return new int[0];
		}

		for (int i = 0; i < activeDrawBuffers.length; i++) {
			RenderPassDescriptor.Attachment<Optional<Vector4fc>> attachment = colorAttachments.get(i);

			if (attachment == null || attachment.textureView() != currentView(activeDrawBuffers[i])) {
				return new int[0];
			}
		}

		return Arrays.copyOf(activeDrawBuffers, activeDrawBuffers.length);
	}

	public static void ensureForFinalPass(CommandEncoder encoder, GpuTexture colorTexture) {
		if (ensure(colorTexture)) {
			frameActive = false;
			currentFrameMainColorCopyAvailable = false;
			loggedCapture = false;
		}

		if (!frameActive && ready()) {
			currentFrameMainColorCopyAvailable = seedTargets(encoder,
				Minecraft.getInstance().gameRenderer.mainRenderTarget().getColorTextureView());
			frameActive = true;
		}
	}

	public static boolean hasCurrentFrameMainColorCopy() {
		return frameActive && currentFrameMainColorCopyAvailable;
	}

	public static boolean canCopyToMain(int target, GpuTexture mainColorTexture) {
		return targetModel.canCopyTo(target, mainColorTexture);
	}

	public static GpuTexture currentTexture(int index) {
		return targetModel.currentTexture(index);
	}

	public static GpuTextureView currentView(int index) {
		return targetModel.currentView(index);
	}

	public static GpuTextureView nextView(int index) {
		return targetModel.nextView(index);
	}

	public static GpuFormat effectiveFormat(int index, GpuFormat plannedFormat) {
		return targetModel.effectiveFormat(index, plannedFormat);
	}

	public static void swap(int index) {
		targetModel.swap(index);
	}

	public static void generateMipmaps(CommandEncoder encoder, int index) {
		targetModel.generateMipmaps(encoder, index);
		mipSamplingEnabled.add(currentTexture(index));
	}

	public static void selectMain(int index) {
		targetModel.select(index, false);
	}

	public static void selectAlt(int index) {
		targetModel.select(index, true);
	}

	public static boolean isAlt(int index) {
		return targetModel.isAlt(index);
	}

	public static void applyExplicitFlips(String pass) {
		targetModel.applyExplicitFlips(pass);
	}

	public static void clearConfiguredTargets(CommandEncoder encoder) {
		targetModel.clearConfiguredTargets(encoder);
	}

	public static void bindSamplers(RenderPass pass, GpuTextureView depthView) {
		bindSamplers(pass, depthView, depthView, depthView);
	}

	public static void bindSamplers(RenderPass pass) {
		bindSamplers(pass, depthTexture0, depthTexture1, depthTexture2);
	}

	public static void bindSamplers(RenderPass pass, GpuTextureView depth0, GpuTextureView depth1, GpuTextureView depth2) {
		if (!ready()) {
			return;
		}

		GpuSampler sampler = RenderSystem.getSamplerCache().getClampToEdge(FilterMode.NEAREST);

		for (int i = 0; i < COLOR_TARGET_COUNT; i++) {
			GpuTextureView view = currentView(i);
			if (view != null) {
				pass.setUniform("colortex" + i, view, samplerForTarget(view));
			}
		}

		bindAlias(pass, "InSampler", FALLBACK_SCENE_TARGET);
		bindAlias(pass, "Sampler0", FALLBACK_SCENE_TARGET);
		bindAlias(pass, "u_MainSampler", FALLBACK_SCENE_TARGET);
		bindAlias(pass, "texture", FALLBACK_SCENE_TARGET);
		bindAlias(pass, "tex", FALLBACK_SCENE_TARGET);
		bindAlias(pass, "composite", 3);
		bindAlias(pass, "gcolor", 0);
		bindAlias(pass, "gdepth", 1);
		bindAlias(pass, "gnormal", 2);
		bindAlias(pass, "gaux1", 4);
		bindAlias(pass, "gaux2", 5);
		bindAlias(pass, "gaux3", 6);
		bindAlias(pass, "gaux4", 7);

		bindDepth(pass, "depthtex0", depth0, sampler);
		bindDepth(pass, "depthtex1", depth1, sampler);
		bindDepth(pass, "depthtex2", depth2, sampler);
		bindDepth(pass, "gdepthtex", depth0, sampler);
	}

	public static void setDepthTextureViews(GpuTextureView depth0, GpuTextureView depth1, GpuTextureView depth2) {
		depthTexture0 = depth0;
		depthTexture1 = depth1;
		depthTexture2 = depth2;
	}

	/** Match Iris render-target sampling: floating/normalized color is linear; integer/depth data is nearest. */
	public static GpuSampler samplerForTarget(GpuTextureView view) {
		boolean nearest = targetNeedsNearest(view.texture().getFormat());
		return RenderSystem.getSamplerCache().getClampToEdge(nearest ? FilterMode.NEAREST : FilterMode.LINEAR,
			!nearest && view.mipLevels() > 1 && mipSamplingEnabled.contains(view.texture()));
	}

	public static boolean isMipSamplingEnabled(GpuTextureView view) {
		return view.mipLevels() > 1 && mipSamplingEnabled.contains(view.texture());
	}

	static boolean targetNeedsNearest(GpuFormat format) {
		return format.hasDepthAspect() || format.hasStencilAspect() || format.name().endsWith("_SINT") || format.name().endsWith("_UINT");
	}

	public static void clearDepthTextureViews() {
		setDepthTextureViews(null, null, null);
	}

	public static GpuTextureView depthSamplerView(String sampler) {
		if (sampler == null) {
			return null;
		}

		return switch (sampler) {
			case "depthtex0", "gdepthtex" -> depthTexture0;
			case "depthtex1" -> depthTexture1;
			case "depthtex2" -> depthTexture2;
			default -> null;
		};
	}

	public static GpuTextureView colorSamplerView(String sampler) {
		int target = colorSamplerTarget(sampler);
		return ready() && target >= 0 ? currentView(target) : null;
	}

	public static int colorSamplerTarget(String sampler) {
		if (sampler == null) {
			return -1;
		}
		return switch (sampler) {
			case "InSampler", "Sampler0", "u_MainSampler", "texture", "tex" -> FALLBACK_SCENE_TARGET;
			default -> IrisVulkanTargetIndices.colorSamplerTarget(sampler);
		};
	}

	public static boolean isCurrentColorAttachment(int target, GpuTextureView view) {
		if (!ready() || target < 0 || target >= COLOR_TARGET_COUNT || view == null) {
			return false;
		}
		return currentView(target) == view;
	}

	public static void finishFrame() {
		mipSamplingEnabled.clear();
		frameOpen = false;
		frameActive = false;
		currentFrameMainColorCopyAvailable = false;
		activeDrawBuffers = Arrays.copyOf(DEFAULT_TERRAIN_DRAW_BUFFERS, DEFAULT_TERRAIN_DRAW_BUFFERS.length);
	}

	public static void close() {
		feedbackPrograms = null;
		feedbackPlan = IrisVulkanFeedbackPlan.unknown("Program set closed");
		mipSamplingEnabled.clear();
		targetModel.close();
		IrisVulkanDepthCopy.close();
		closeDepthSnapshots();
		for (int i=0; i<COLOR_TARGET_COUNT; ++i) {
			if (feedbackViews[i] != null) feedbackViews[i].close();
			if (feedbackSnapshots[i] != null) feedbackSnapshots[i].close();
			feedbackViews[i] = null;
			feedbackSnapshots[i] = null;
		}
		frameOpen = false;
		frameActive = false;
		currentFrameMainColorCopyAvailable = false;
		activeDrawBuffers = Arrays.copyOf(DEFAULT_TERRAIN_DRAW_BUFFERS, DEFAULT_TERRAIN_DRAW_BUFFERS.length);
		loggedCapture = false;
		loggedCaptureRejections.clear();
		clearDepthTextureViews();
	}

	private static WorldRenderingPhase currentTerrainCapturePhase() {
		WorldRenderingPipeline pipeline = Iris.getPipelineManager().getPipelineNullable();
		WorldRenderingPhase phase = pipeline == null ? WorldRenderingPhase.NONE : pipeline.getPhase();

		return phase == WorldRenderingPhase.TERRAIN_SOLID
			|| phase == WorldRenderingPhase.TERRAIN_CUTOUT
			|| phase == WorldRenderingPhase.TERRAIN_CUTOUT_MIPPED
			? phase
			: WorldRenderingPhase.NONE;
	}

	private static RenderPassDescriptor rejectCapture(RenderPassDescriptor descriptor, String reason) {
        rejectCapture(reason);
        return descriptor;
    }

    private static boolean rejectCapture(String reason) {
		if (Boolean.getBoolean("iris.vulkan.logGbufferCaptureRejects") && loggedCaptureRejections.add(reason)) {
			Iris.logger.info("Native Vulkan gbuffer capture rejected once: {}.", reason);
		}
		return false;
	}

	private static boolean isMainSizedColorTarget(GpuTexture candidate, GpuTexture mainColorTexture) {
		if (candidate == null || candidate.isClosed() || mainColorTexture == null || mainColorTexture.isClosed()) {
			return false;
		}

		return candidate.getWidth(0) == mainColorTexture.getWidth(0)
			&& candidate.getHeight(0) == mainColorTexture.getHeight(0)
			&& candidate.getFormat() == mainColorTexture.getFormat()
			&& (candidate.usage() & GpuTexture.USAGE_COPY_SRC) != 0;
	}

	private static boolean shouldSkipCaptureLabel(String label) {
		if (label == null) {
			return false;
		}

		String normalized = label.toLowerCase(java.util.Locale.ROOT);
		return normalized.contains("sky")
			|| normalized.contains("cloud")
			|| normalized.contains("weather")
			|| normalized.contains("particle")
			|| normalized.contains("entity")
			|| normalized.contains("outline")
			|| normalized.contains("gui")
			|| normalized.contains("vignette")
			|| normalized.contains("crosshair")
			|| normalized.contains("blur")
			|| normalized.contains("lightmap")
			|| normalized.contains("sun")
			|| normalized.contains("moon")
			|| normalized.contains("stars")
			|| normalized.contains("horizon");
	}

	private static boolean ensure(GpuTexture source) {
		if (source == null || source.isClosed()) {
			return false;
		}

		ProgramSet programSet = Iris.getCurrentPack()
			.map(pack -> pack.getProgramSet(Iris.getCurrentDimension()))
			.orElse(null);
		if (programSet != feedbackPrograms) {
			feedbackPrograms = programSet;
			try { feedbackPlan = IrisVulkanFeedbackPlan.fromPrograms(programSet); }
			catch (RuntimeException failure) { feedbackPlan = IrisVulkanFeedbackPlan.unknown("Cannot establish sampler contract: " + failure.getMessage()); }
			Iris.logger.info("Native Vulkan world feedback snapshots: targets={}, conservativeFallback={}, programs={}, reason={}",
				feedbackPlan.targets(), feedbackPlan.conservativeFallback(), feedbackPlan.programCount(), feedbackPlan.reason());
		}
		if (programSet == null) {
			return targetModel.configureDefaults(source.getWidth(0), source.getHeight(0), source.getFormat());
		} else {
			return targetModel.configure(programSet, source.getWidth(0), source.getHeight(0), source.getFormat());
		}
	}

	private static boolean ready() {
		return targetModel.ready();
	}

	private static boolean validDrawBuffers(int[] drawBuffers) {
		try {
			IrisVulkanTargetIndices.validateDrawBuffers("gbuffer pass", drawBuffers);
			return true;
		} catch (IllegalArgumentException ignored) {
			return false;
		}
	}

	private static boolean seedTargets(CommandEncoder encoder, GpuTextureView colorTextureView) {
		return targetModel.seed(encoder, colorTextureView);
	}

	private static void bindAlias(RenderPass pass, String name, int target) {
		GpuTextureView view = currentView(target);
		if (view != null) {
			pass.setUniform(name, view, samplerForTarget(view));
		}
	}

	private static void bindDepth(RenderPass pass, String name, GpuTextureView view, GpuSampler sampler) {
		if (view != null && !view.isClosed()) {
			pass.setUniform(name, view, sampler);
		}
	}
}
